import type { Character } from '@/types/character';
import { SCHEMA_VERSION } from './constants';

/**
 * Personagem de exemplo: Tharivol, Elfo da Floresta, Guerreiro nível 3.
 * Todos os valores são brutos — modificadores são sempre derivados na camada de render.
 */
export const defaultCharacter: Character = {
  id: 'default-tharivol',
  versaoSchema: SCHEMA_VERSION,
  identificacao: {
    nome: 'Tharivol Lúmen',
    raca: 'Elfo',
    subRaca: 'Elfo da Floresta',
    classe: 'Guerreiro',
    nivel: 3,
    antecedente: 'Soldado',
    xp: 900,
    inspiracao: false,
  },
  combate: {
    dadoDeVida: 'd10',
    dadosDeVidaDisponiveis: 3,
    pontosVidaMax: 28,
    pontosVidaAtual: 22,
    pontosVidaTemporarios: 0,
    classeArmadura: 16,
    deslocamento: 10,
  },
  testesMorte: {
    sucessos: 0,
    falhas: 0,
  },
  atributos: {
    forca: { valor: 16 },
    destreza: { valor: 14 },
    constituicao: { valor: 14 },
    inteligencia: { valor: 10 },
    sabedoria: { valor: 12 },
    carisma: { valor: 8 },
  },
  testesResistencia: {
    forca: { proficiente: true },
    destreza: { proficiente: false },
    constituicao: { proficiente: true },
    inteligencia: { proficiente: false },
    sabedoria: { proficiente: false },
    carisma: { proficiente: false },
  },
  pericias: {
    acrobacia: { proficiente: false, atributo: 'destreza' },
    arcanismo: { proficiente: false, atributo: 'inteligencia' },
    atletismo: {
      proficiente: true,
      especialidade: true,
      atributo: 'forca',
    },
    atuacao: { proficiente: false, atributo: 'carisma' },
    enganacao: { proficiente: false, atributo: 'carisma' },
    furtividade: { proficiente: false, atributo: 'destreza' },
    historia: { proficiente: false, atributo: 'inteligencia' },
    intimidacao: { proficiente: true, atributo: 'carisma' },
    intuicao: { proficiente: false, atributo: 'sabedoria' },
    investigacao: { proficiente: false, atributo: 'inteligencia' },
    lidarComAnimais: { proficiente: false, atributo: 'sabedoria' },
    medicina: { proficiente: false, atributo: 'sabedoria' },
    natureza: { proficiente: false, atributo: 'inteligencia' },
    percepcao: { proficiente: true, atributo: 'sabedoria' },
    persuasao: { proficiente: false, atributo: 'carisma' },
    prestidigitacao: { proficiente: false, atributo: 'destreza' },
    religiao: { proficiente: false, atributo: 'inteligencia' },
    sobrevivencia: { proficiente: true, atributo: 'sabedoria' },
  },
  magias: {
    atributoConjuracao: null,
    slots: {
      1: { total: 0, usados: 0 },
      2: { total: 0, usados: 0 },
      3: { total: 0, usados: 0 },
      4: { total: 0, usados: 0 },
      5: { total: 0, usados: 0 },
      6: { total: 0, usados: 0 },
      7: { total: 0, usados: 0 },
      8: { total: 0, usados: 0 },
      9: { total: 0, usados: 0 },
    },
    slotsPacto: null,
    magiasConhecidas: [],
  },
  habilidades: [
    {
      id: 'h1',
      nome: 'Surto de Ação',
      descricao:
        'Pode tomar uma ação adicional em seu turno, além da ação normal e de quaisquer ações bônus.',
      usosMaximos: 1,
      usosAtuais: 1,
      recuperaEm: 'descanso_curto',
    },
    {
      id: 'h2',
      nome: 'Segundo Fôlego',
      descricao:
        'Pode usar uma ação bônus para recuperar pontos de vida iguais a 1d10 + seu nível de guerreiro.',
      usosMaximos: 1,
      usosAtuais: 1,
      recuperaEm: 'descanso_curto',
    },
    {
      id: 'h3',
      nome: 'Estilo de Combate: Defesa',
      descricao:
        '+1 na CA enquanto usa armadura.',
      usosMaximos: null,
      usosAtuais: 0,
      recuperaEm: 'nunca',
    },
    {
      id: 'h4',
      nome: 'Arquétipo Marcial: Campeão — Crítico Melhorado',
      descricao:
        'Seus ataques com armas causam acerto crítico em 19 ou 20.',
      usosMaximos: null,
      usosAtuais: 0,
      recuperaEm: 'nunca',
    },
  ],
  inventario: [
    {
      id: 'i1',
      nome: 'Cota de Malha',
      quantidade: 1,
      pesoKg: 20,
      equipado: true,
      descricao: 'CA 14 + modificador de DES (máx 2).',
    },
    {
      id: 'i2',
      nome: 'Escudo',
      quantidade: 1,
      pesoKg: 3,
      equipado: true,
      descricao: '+2 na CA enquanto equipado.',
    },
    {
      id: 'i3',
      nome: 'Espada Longa',
      quantidade: 1,
      pesoKg: 1.5,
      equipado: true,
      descricao: '1d8 cortante (1d10 a duas mãos). Versátil.',
    },
    {
      id: 'i4',
      nome: 'Arco Longo',
      quantidade: 1,
      pesoKg: 1,
      equipado: false,
      descricao: '1d8 perfurante. Alcance 45/180m.',
    },
    {
      id: 'i5',
      nome: 'Flechas',
      quantidade: 20,
      pesoKg: 0.05,
      equipado: false,
    },
    {
      id: 'i6',
      nome: 'Poção de Cura',
      quantidade: 2,
      pesoKg: 0.25,
      equipado: false,
      descricao: 'Recupera 2d4+2 PV.',
    },
    {
      id: 'i7',
      nome: 'Rações (dias)',
      quantidade: 5,
      pesoKg: 0.25,
      equipado: false,
    },
  ],
  atualizadoEm: new Date().toISOString(),
};
